// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoWRYC-zAF99t1R347wKnh5PhsBXeG4qo',
    appId: '1:164793303675:web:105ef3c886ba1fb44298de',
    messagingSenderId: '164793303675',
    projectId: 'safezone-11724',
    authDomain: 'safezone-11724.firebaseapp.com',
    storageBucket: 'safezone-11724.firebasestorage.app',
    measurementId: 'G-NF9L0G89E8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDl_A_iTFxfKwPJNyDKhmdOtt6GQKisKuU',
    appId: '1:164793303675:android:6fabeec660d7206f4298de',
    messagingSenderId: '164793303675',
    projectId: 'safezone-11724',
    storageBucket: 'safezone-11724.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDN0LlAPK0LACyoijAbHowju4Wxl-E_AgA',
    appId: '1:164793303675:ios:4667d0e212f838514298de',
    messagingSenderId: '164793303675',
    projectId: 'safezone-11724',
    storageBucket: 'safezone-11724.firebasestorage.app',
    iosBundleId: 'com.example.safezone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDN0LlAPK0LACyoijAbHowju4Wxl-E_AgA',
    appId: '1:164793303675:ios:4667d0e212f838514298de',
    messagingSenderId: '164793303675',
    projectId: 'safezone-11724',
    storageBucket: 'safezone-11724.firebasestorage.app',
    iosBundleId: 'com.example.safezone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAoWRYC-zAF99t1R347wKnh5PhsBXeG4qo',
    appId: '1:164793303675:web:97575fe59606fc9c4298de',
    messagingSenderId: '164793303675',
    projectId: 'safezone-11724',
    authDomain: 'safezone-11724.firebaseapp.com',
    storageBucket: 'safezone-11724.firebasestorage.app',
    measurementId: 'G-JFXQK5ETTK',
  );
}
